package com.github.pdaodao.springwebplus.tool.db.core;


/**
 * sql 类型
 */
public enum SqlType {
    // CREATE TABLE, CREATE DATABASE, CREATE FUNCTION, CREATE CATALOG
    CREATE,
    // DROP TABLE, DROP DATABASE, DROP FUNCTION, DROP CATALOG, DROP VIEW
    DROP,
    // ALTER TABLE, ALTER DATABASE, ALTER FUNCTION
    ALTER,
    // USE CATALOG, USE [CATALOG.]DATABASE, USE MODULES
    USE,
    // LOAD MODULE
    LOAD,
    // UNLOAD MODULE
    UNLOAD,
    //SHOW CATALOGS, SHOW DATABASES, SHOW TABLES, SHOW [USER] FUNCTIONS, SHOW PARTITIONSCREATE VIEW, SHOW VIEWS, SHOW [FULL] MODULES
    SHOW,
    INSERT,
    UPDATE,
    DELETE,
    DESCRIBE,
    SELECT,
    CDC, // cdc 全库同步
    UNKOWN,
    SET,
    UNSET,
    COMMENT
}
